# default properties
server:
  port: 5000

app:
  name: bundle-management
  dir: ${user.home}/.${app.name}
  db-name: bundles
  db-host: localhost
  db-port: 5432
  db-url-prefix: jdbc:postgresql://

spring:  
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${app.db-url-prefix}${app.db-host}:${app.db-port}/${app.db-name}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
      show_sql: true
      use_sql_comments: true
      generate_statistics: false
