# default properties

environment: dev

server:
  port: 8080

logging:
  level:
    .: debug
    org.springframework: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql: trace
  file:
    name: ${HOME}/logs/bundle-management.log

app:
  name: bundle-management
  api-info-title: Resourcebundles REST API
  api-info-description: REST API for manage several resourcebundles applications
  api-info-version: /v1
  api-info-license: MIT
  api-info-license-url: https://opensource.org/licenses/MIT
  contact-name: bundlemanagement inc.
  contact-url: www.bundlemanagement.org
  contact-email: info@bundlemanagement.org
  base-package: io.github.astrapi69.bundlemanagement
  docket-paths-regex: /v1/.*|
  dir: ${user.home}/.${app.name}
  db-name: bundles
  db-host: localhost
  db-port: 5432
  db-url-prefix: jdbc:postgresql://
  db-username: postgres
  db-password: postgres

spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${app.db-url-prefix}${app.db-host}:${app.db-port}/${app.db-name}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
      show_sql: true
      use_sql_comments: true
      generate_statistics: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  sql:
    init:
      mode: never
